// Sender Service gRPC API (§4.1 ТЗ).
//
// Версионирование: имя пакета содержит v1. Несовместимые изменения
// делаются в новом пакете nexus.sender.v2 — оба сервиса могут быть
// зарегистрированы параллельно.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/sender/v1/sender.proto

package senderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthConfig — параметры авторизации внешнего узла, разрешённой к этому
// конкретному запросу. Receiver уже разобрался с auth_type и собрал
// итоговый заголовок Authorization (или ничего, если auth_type=none).
type AuthConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Готовое значение заголовка Authorization, либо пустая строка.
	// В таком виде Sender ничего не знает про режимы — просто пробрасывает.
	AuthorizationHeader string `protobuf:"bytes,1,opt,name=authorization_header,json=authorizationHeader,proto3" json:"authorization_header,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_proto_sender_v1_sender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sender_v1_sender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_proto_sender_v1_sender_proto_rawDescGZIP(), []int{0}
}

func (x *AuthConfig) GetAuthorizationHeader() string {
	if x != nil {
		return x.AuthorizationHeader
	}
	return ""
}

type SendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // UUID запроса, прокидываемый из Receiver'а
	NodePath       string                 `protobuf:"bytes,2,opt,name=node_path,json=nodePath,proto3" json:"node_path,omitempty"`    // для логов и трассировки
	TargetUrl      string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"` // фактический URL (после URL resolution)
	Method         string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                        // HTTP-метод (POST, GET, PUT, ...)
	Auth           *AuthConfig            `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // forward_headers + Content-Type и т.п.
	Body           []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	TimeoutMs      int32                  `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	RetryCount     int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryBackoffMs int32                  `protobuf:"varint,10,opt,name=retry_backoff_ms,json=retryBackoffMs,proto3" json:"retry_backoff_ms,omitempty"`
	// Для логирования в ClickHouse-таблицу узла.
	ClickhouseTable string `protobuf:"bytes,20,opt,name=clickhouse_table,json=clickhouseTable,proto3" json:"clickhouse_table,omitempty"`
	LogRequestBody  bool   `protobuf:"varint,21,opt,name=log_request_body,json=logRequestBody,proto3" json:"log_request_body,omitempty"`
	LogResponseBody bool   `protobuf:"varint,22,opt,name=log_response_body,json=logResponseBody,proto3" json:"log_response_body,omitempty"`
	LogHeaders      bool   `protobuf:"varint,23,opt,name=log_headers,json=logHeaders,proto3" json:"log_headers,omitempty"`
	ClientIp        string `protobuf:"bytes,24,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// §22: контроль логирования узла.
	LoggingEnabled     bool  `protobuf:"varint,25,opt,name=logging_enabled,json=loggingEnabled,proto3" json:"logging_enabled,omitempty"`                 // false → лог в ClickHouse не пишется совсем
	MaxBodySizeEnabled bool  `protobuf:"varint,26,opt,name=max_body_size_enabled,json=maxBodySizeEnabled,proto3" json:"max_body_size_enabled,omitempty"` // включает обрезку сохраняемых тел
	MaxBodySize        int32 `protobuf:"varint,27,opt,name=max_body_size,json=maxBodySize,proto3" json:"max_body_size,omitempty"`                        // макс. число символов (рун) в request/response
	// §37: UUID узла — пишется в колонку node_id лог-таблицы, чтобы различать узлы,
	// делящие одну ClickHouse-таблицу (per-node атрибуция метрик/логов/очистки).
	NodeId string `protobuf:"bytes,28,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// §39: подпуть запроса (хвост path-passthrough после пути узла), напр.
	// "v1/GetParcelsInfo". Пишется в колонку `method` лог-таблицы. Пусто у
	// обычных узлов. HTTP-глагол по-прежнему в поле method (= колонка http_method).
	RequestPath string `protobuf:"bytes,29,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	// §55: вызов — тестовый (dry-run из UI), а не боевой трафик. Sender выполняет
	// реальный HTTP-запрос тем же клиентом, но НЕ оставляет следов на узле:
	//   - не пишет лог в ClickHouse (двойной гейт вместе с logging_enabled);
	//   - не пишет метрики (§6) и gauge исхода последнего вызова (§41/§52);
	//   - не персистит статус узла в Redis (§46);
	//   - не трогает circuit breaker (§9.5/§50.4) — ни Allow, ни Record*.
	//
	// Иначе тест конфига по мёртвому адресу покрасил бы живой узел в Down и открыл
	// его breaker, начав отдавать 503 боевому трафику. Порядок деплоя: Sender → Web
	// (старый Sender поле проигнорирует и побочку не погасит).
	DryRun        bool `protobuf:"varint,30,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_proto_sender_v1_sender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sender_v1_sender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_proto_sender_v1_sender_proto_rawDescGZIP(), []int{1}
}

func (x *SendRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendRequest) GetNodePath() string {
	if x != nil {
		return x.NodePath
	}
	return ""
}

func (x *SendRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *SendRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendRequest) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *SendRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SendRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SendRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SendRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *SendRequest) GetRetryBackoffMs() int32 {
	if x != nil {
		return x.RetryBackoffMs
	}
	return 0
}

func (x *SendRequest) GetClickhouseTable() string {
	if x != nil {
		return x.ClickhouseTable
	}
	return ""
}

func (x *SendRequest) GetLogRequestBody() bool {
	if x != nil {
		return x.LogRequestBody
	}
	return false
}

func (x *SendRequest) GetLogResponseBody() bool {
	if x != nil {
		return x.LogResponseBody
	}
	return false
}

func (x *SendRequest) GetLogHeaders() bool {
	if x != nil {
		return x.LogHeaders
	}
	return false
}

func (x *SendRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SendRequest) GetLoggingEnabled() bool {
	if x != nil {
		return x.LoggingEnabled
	}
	return false
}

func (x *SendRequest) GetMaxBodySizeEnabled() bool {
	if x != nil {
		return x.MaxBodySizeEnabled
	}
	return false
}

func (x *SendRequest) GetMaxBodySize() int32 {
	if x != nil {
		return x.MaxBodySize
	}
	return 0
}

func (x *SendRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SendRequest) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *SendRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type SendResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body       []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers    map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Заполняется, если внешний узел не ответил (timeout, dns, и т.п.).
	// Receiver проксирует это как 502/504/503.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Attempts      int32  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	DurationMs    int32  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_proto_sender_v1_sender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sender_v1_sender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_sender_v1_sender_proto_rawDescGZIP(), []int{2}
}

func (x *SendResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SendResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SendResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SendResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *SendResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_sender_v1_sender_proto protoreflect.FileDescriptor

const file_proto_sender_v1_sender_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/sender/v1/sender.proto\x12\x0fnexus.sender.v1\"?\n" +
	"\n" +
	"AuthConfig\x121\n" +
	"\x14authorization_header\x18\x01 \x01(\tR\x13authorizationHeader\"\xb5\x06\n" +
	"\vSendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tnode_path\x18\x02 \x01(\tR\bnodePath\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12/\n" +
	"\x04auth\x18\x05 \x01(\v2\x1b.nexus.sender.v1.AuthConfigR\x04auth\x12C\n" +
	"\aheaders\x18\x06 \x03(\v2).nexus.sender.v1.SendRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x05R\ttimeoutMs\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12(\n" +
	"\x10retry_backoff_ms\x18\n" +
	" \x01(\x05R\x0eretryBackoffMs\x12)\n" +
	"\x10clickhouse_table\x18\x14 \x01(\tR\x0fclickhouseTable\x12(\n" +
	"\x10log_request_body\x18\x15 \x01(\bR\x0elogRequestBody\x12*\n" +
	"\x11log_response_body\x18\x16 \x01(\bR\x0flogResponseBody\x12\x1f\n" +
	"\vlog_headers\x18\x17 \x01(\bR\n" +
	"logHeaders\x12\x1b\n" +
	"\tclient_ip\x18\x18 \x01(\tR\bclientIp\x12'\n" +
	"\x0flogging_enabled\x18\x19 \x01(\bR\x0eloggingEnabled\x121\n" +
	"\x15max_body_size_enabled\x18\x1a \x01(\bR\x12maxBodySizeEnabled\x12\"\n" +
	"\rmax_body_size\x18\x1b \x01(\x05R\vmaxBodySize\x12\x17\n" +
	"\anode_id\x18\x1c \x01(\tR\x06nodeId\x12!\n" +
	"\frequest_path\x18\x1d \x01(\tR\vrequestPath\x12\x17\n" +
	"\adry_run\x18\x1e \x01(\bR\x06dryRun\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"\fSendResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12D\n" +
	"\aheaders\x18\x03 \x03(\v2*.nexus.sender.v1.SendResponse.HeadersEntryR\aheaders\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x05R\n" +
	"durationMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012T\n" +
	"\rSenderService\x12C\n" +
	"\x04Send\x12\x1c.nexus.sender.v1.SendRequest\x1a\x1d.nexus.sender.v1.SendResponseB Z\x1enexus/proto/sender/v1;senderv1b\x06proto3"

var (
	file_proto_sender_v1_sender_proto_rawDescOnce sync.Once
	file_proto_sender_v1_sender_proto_rawDescData []byte
)

func file_proto_sender_v1_sender_proto_rawDescGZIP() []byte {
	file_proto_sender_v1_sender_proto_rawDescOnce.Do(func() {
		file_proto_sender_v1_sender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sender_v1_sender_proto_rawDesc), len(file_proto_sender_v1_sender_proto_rawDesc)))
	})
	return file_proto_sender_v1_sender_proto_rawDescData
}

var file_proto_sender_v1_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_sender_v1_sender_proto_goTypes = []any{
	(*AuthConfig)(nil),   // 0: nexus.sender.v1.AuthConfig
	(*SendRequest)(nil),  // 1: nexus.sender.v1.SendRequest
	(*SendResponse)(nil), // 2: nexus.sender.v1.SendResponse
	nil,                  // 3: nexus.sender.v1.SendRequest.HeadersEntry
	nil,                  // 4: nexus.sender.v1.SendResponse.HeadersEntry
}
var file_proto_sender_v1_sender_proto_depIdxs = []int32{
	0, // 0: nexus.sender.v1.SendRequest.auth:type_name -> nexus.sender.v1.AuthConfig
	3, // 1: nexus.sender.v1.SendRequest.headers:type_name -> nexus.sender.v1.SendRequest.HeadersEntry
	4, // 2: nexus.sender.v1.SendResponse.headers:type_name -> nexus.sender.v1.SendResponse.HeadersEntry
	1, // 3: nexus.sender.v1.SenderService.Send:input_type -> nexus.sender.v1.SendRequest
	2, // 4: nexus.sender.v1.SenderService.Send:output_type -> nexus.sender.v1.SendResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sender_v1_sender_proto_init() }
func file_proto_sender_v1_sender_proto_init() {
	if File_proto_sender_v1_sender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sender_v1_sender_proto_rawDesc), len(file_proto_sender_v1_sender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sender_v1_sender_proto_goTypes,
		DependencyIndexes: file_proto_sender_v1_sender_proto_depIdxs,
		MessageInfos:      file_proto_sender_v1_sender_proto_msgTypes,
	}.Build()
	File_proto_sender_v1_sender_proto = out.File
	file_proto_sender_v1_sender_proto_goTypes = nil
	file_proto_sender_v1_sender_proto_depIdxs = nil
}
