// Sender Service gRPC API (§4.1 ТЗ).
//
// Версионирование: имя пакета содержит v1. Несовместимые изменения
// делаются в новом пакете nexus.sender.v2 — оба сервиса могут быть
// зарегистрированы параллельно.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: proto/sender/v1/sender.proto

package senderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SenderService_Send_FullMethodName = "/nexus.sender.v1.SenderService/Send"
)

// SenderServiceClient is the client API for SenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SenderServiceClient interface {
	// Send выполняет один outbound-вызов внешнего узла.
	// Используется Receiver'ом для синхронных запросов (/v1/request/*).
	// Для async (/v1/requestAsync/*) Sender забирает сообщения из Kafka.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type senderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSenderServiceClient(cc grpc.ClientConnInterface) SenderServiceClient {
	return &senderServiceClient{cc}
}

func (c *senderServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, SenderService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SenderServiceServer is the server API for SenderService service.
// All implementations must embed UnimplementedSenderServiceServer
// for forward compatibility.
type SenderServiceServer interface {
	// Send выполняет один outbound-вызов внешнего узла.
	// Используется Receiver'ом для синхронных запросов (/v1/request/*).
	// Для async (/v1/requestAsync/*) Sender забирает сообщения из Kafka.
	Send(context.Context, *SendRequest) (*SendResponse, error)
	mustEmbedUnimplementedSenderServiceServer()
}

// UnimplementedSenderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSenderServiceServer struct{}

func (UnimplementedSenderServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedSenderServiceServer) mustEmbedUnimplementedSenderServiceServer() {}
func (UnimplementedSenderServiceServer) testEmbeddedByValue()                       {}

// UnsafeSenderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SenderServiceServer will
// result in compilation errors.
type UnsafeSenderServiceServer interface {
	mustEmbedUnimplementedSenderServiceServer()
}

func RegisterSenderServiceServer(s grpc.ServiceRegistrar, srv SenderServiceServer) {
	// If the following call panics, it indicates UnimplementedSenderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SenderService_ServiceDesc, srv)
}

func _SenderService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SenderService_ServiceDesc is the grpc.ServiceDesc for SenderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SenderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.sender.v1.SenderService",
	HandlerType: (*SenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SenderService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sender/v1/sender.proto",
}
