global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - prometheus.alerts.yml

scrape_configs:
  - job_name: nexus-receiver
    static_configs:
      - targets: ["receiver:8080"]
    metrics_path: /metrics

  - job_name: nexus-sender
    static_configs:
      - targets: ["sender:9091"]
    metrics_path: /metrics

  - job_name: nexus-web
    static_configs:
      - targets: ["web:8000"]
    metrics_path: /metrics
