Server:
  Port: "8090"

DataBase:
  Type: "postgres"
  Host: ""
  Port: 
  DBName: "bus"
  Credintials:
    UserName: ""
    Password: ""

Metrics:
  Interval: 15

Redis:
  Use: true
  Addr: ""
  DB: 14
  Credintials:
    UserName: ""
    Password: ""

Log:
  Debug: true
  Level: 5            # Уровень логирования от 2 до 5, где 2 - ошибка, 3 - предупреждение, 4 - информация, 5 - дебаг
  OutputInFile: false # включить логирование в каталог LogDir
  Dir: "logs"         # каталог логов
  
DeleteTempFiles: false # Удалать файлы из web/temp

Sentry:
  Use: false # Включить sentry для отлова внутренних ошибок
  Environment: "Debug"
  AttachStacktrace: true
  TracesSampleRate: 1.0
  EnableTracing: true
  Debug: true