// Package web Code generated by swaggo/swag. DO NOT EDIT
package web

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/audit": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "description": "Поддерживаемые actions: node.create/update/delete, user.create/update/delete/password_changed, token.create/revoke/delete, login.success/failure, ch_table.drop, settings.update и др.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Журнал audit-log (admin only, §7.13).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "фильтр по user_id",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "одно значение action",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "несколько action через запятую",
                        "name": "actions",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "node|user|token|ch_table|...",
                        "name": "target_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "фильтр по target_id",
                        "name": "target_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 (начало)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 (конец)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 100, max 1000",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/audit/export.csv": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "description": "Тот же набор фильтров, что у /api/audit. Default limit 10000, max 50000. CSV в UTF-8 с BOM (для Excel), 9 колонок: id, created_at, user_login, user_id, action, target_type, target_id, ip_address, details (JSON).",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Выгрузка audit-log в CSV (admin only, §7.13).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "фильтр по user_id",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "одно значение action",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "несколько action через запятую",
                        "name": "actions",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "node|user|token|ch_table|...",
                        "name": "target_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "фильтр по target_id",
                        "name": "target_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 (начало)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 (конец)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 10000, max 50000",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "При успехе ставит HttpOnly cookie nexus_session (§7.1 ТЗ).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Логин по логину/паролю.",
                "parameters": [
                    {
                        "description": "credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "invalid credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "user inactive",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Удаляет session-cookie nexus_session и инвалидирует токен в Redis (§7.1 ТЗ).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Завершить сессию.",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "description": "Возвращает user_id, login, email, role, lang и must_change_password.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Профиль текущей сессии.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/logs/{id}/replay": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Берёт оригинал из ClickHouse-лога, применяет переопределения, отправляет через Receiver.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Повторно отправить запрос через шину (§7.4.1).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "log id (UUID v4)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "опции",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.ReplayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nexus_internal_web_usecase.ReplayResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "node disabled",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "rate limit exceeded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/nodes": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Список узлов команды.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "поиск по path или target_url",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "request | requestAsync",
                        "name": "root_method",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "лимит, max 500",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Только admin. §3.3 ТЗ, лимиты в §3.3.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Создать узел.",
                "parameters": [
                    {
                        "description": "node config",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.CreateNodeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.NodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "path already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/nodes/dry-run": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Прогоняет synthetic-запрос через pipeline шины и возвращает пошаговый отчёт.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Dry-run: проверить конфиг узла без сохранения (§7.5.1).",
                "parameters": [
                    {
                        "description": "node + sub-request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.DryRunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nexus_internal_web_usecase.DryRunReport"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/nodes/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Один узел по id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.NodeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Только admin. Пустые auth_credentials/incoming_auth_credentials в body означают «оставить старое значение» (§5.5 ТЗ).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Обновить узел.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "node config",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.UpdateNodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.NodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "path already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Только admin. Удаляет запись и инвалидирует Redis-кеш. ClickHouse-таблица узла остаётся (см. §7.10 — orphan-cleanup).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Удалить узел.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/nodes/{id}/logs": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Snapshot логов узла из ClickHouse с фильтрами.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "legacy cursor по date_request (UnixMilli); если задан — фильтры from/to/ip/host/status/done/q игнорируются",
                        "name": "since_ms",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "1..500, default 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "начало диапазона (RFC3339 или UnixMilli)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "конец диапазона (RFC3339 или UnixMilli)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "exact match по IP клиента",
                        "name": "ip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "exact match по Host",
                        "name": "host",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ok | err | (пусто)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "yes | no | (пусто)",
                        "name": "done",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "подстрока (case-insensitive) по url/request/response",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/nodes/{id}/logs/stream": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Доступно только UI-сессиям (API-токены отклоняются — §7.14). Каждое новое событие приходит как SSE event \"log\".",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "SSE live-tail логов узла (§7.4).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "event-stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/settings/app": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Возвращает merge'нутые значения из БД. Секреты (DSN, password) маскируются.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Текущие dynamic-настройки Sentry/ClickHouse (§14.5).",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nexus_internal_domain.AppSettings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Patch-семантика: nil-поля сохраняются как есть, \"***\" в секретах не перезаписывает текущее значение.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Обновить dynamic-настройки Sentry/ClickHouse (§14.5).",
                "parameters": [
                    {
                        "description": "patch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nexus_internal_domain.AppSettings"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/settings/clickhouse/orphans": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Возвращает таблицы из текущей CH-базы, у которых нет соответствующего узла в Postgres.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Поиск orphan-таблиц в ClickHouse (§7.10).",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/settings/clickhouse/orphans/{table}": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "DROP TABLE IF EXISTS db.table. Защита: имя валидируется, повторно проверяется orphan-статус, действие пишется в audit.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Удалить orphan-таблицу (§7.10).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Полное имя db.table",
                        "name": "table",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/settings/clickhouse/test": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Открывает временный conn с merge'нутыми (current + body) настройками, делает Ping, возвращает {ok,latency_ms} или {ok:false,error}. Не сохраняет.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Проверить соединение с ClickHouse по patch'у настроек (§7.10).",
                "parameters": [
                    {
                        "description": "patch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nexus_internal_domain.ClickHouseSettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nexus_internal_web_usecase.TestResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/settings/sentry/test": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Создаёт изолированный sentry.Client, отправляет CaptureMessage, ждёт Flush. Глобальный hub не затрагивается. Возвращает {ok,latency_ms} или {ok:false,error}.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Отправить тестовое событие в Sentry с patch'ем настроек (§7.10).",
                "parameters": [
                    {
                        "description": "patch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/nexus_internal_domain.SentrySettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nexus_internal_web_usecase.TestResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tokens": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Каждый видит только свои токены. Возвращает префикс, scopes, last_used_at — без полной строки токена.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Список API-токенов текущего пользователя (§7.14).",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Plain-строка токена возвращается ровно один раз, потом доступен только префикс. Scopes — подмножество {logs:read, nodes:read, metrics:read, audit:read}.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Создать API-токен (§7.14).",
                "parameters": [
                    {
                        "description": "name + scopes + expires_at",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.createTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "token (plain) + info",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tokens/{id}": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Удаление допустимо, только если токен уже revoked. Иначе — 404 «not deletable yet».",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Удалить API-токен.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tokens/{id}/revoke": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "После revoke токен сразу теряет силу, но сама запись остаётся (для аудита).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Отозвать API-токен.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Список пользователей (admin only).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "поиск по login или email",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя (admin only).",
                "parameters": [
                    {
                        "description": "user fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.createUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.userResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "login already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Один пользователь по id (admin only).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.userResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Нельзя демоутить себя в viewer и нельзя оставлять \u003c1 активного admin (§7.9).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Обновить пользователя (admin only).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.updateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.userResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "cannot demote yourself",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Нельзя удалить себя и нельзя оставить \u003c1 активного admin (§7.9).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Удалить пользователя (admin only).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/{id}/password": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Если must_change_password=true, при следующем логине пользователь будет обязан задать новый пароль.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Сменить пароль пользователя (admin only).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_web_adapter_in_http.CreateNodeRequest": {
            "type": "object",
            "required": [
                "path",
                "root_method"
            ],
            "properties": {
                "auth_credentials": {
                    "type": "string",
                    "maxLength": 1024
                },
                "auth_dynamic_field": {
                    "type": "string",
                    "maxLength": 64
                },
                "auth_dynamic_source": {
                    "type": "string",
                    "enum": [
                        "query",
                        "header",
                        "body"
                    ]
                },
                "auth_dynamic_strip_prefix": {
                    "type": "string",
                    "maxLength": 64
                },
                "auth_type": {
                    "type": "string",
                    "enum": [
                        "none",
                        "basic",
                        "token",
                        "token_from_request",
                        "basic_from_request"
                    ]
                },
                "clickhouse_retention_days": {
                    "type": "integer",
                    "maximum": 3650,
                    "minimum": 0
                },
                "clickhouse_table": {
                    "type": "string",
                    "maxLength": 129
                },
                "forward_headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "incoming_auth_credentials": {
                    "type": "string",
                    "maxLength": 1024
                },
                "incoming_auth_type": {
                    "type": "string",
                    "enum": [
                        "none",
                        "basic",
                        "token",
                        "webhook_signature"
                    ]
                },
                "log_headers": {
                    "type": "boolean"
                },
                "log_request_body": {
                    "type": "boolean"
                },
                "log_response_body": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string",
                    "maxLength": 255
                },
                "retry_backoff_ms": {
                    "type": "integer"
                },
                "retry_count": {
                    "type": "integer"
                },
                "root_method": {
                    "type": "string",
                    "enum": [
                        "request",
                        "requestAsync"
                    ]
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "enabled",
                        "disabled",
                        "paused"
                    ]
                },
                "target_url": {
                    "type": "string",
                    "maxLength": 2048
                },
                "timeout_ms": {
                    "type": "integer"
                },
                "url_allowed_hosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url_mode": {
                    "type": "string",
                    "enum": [
                        "static",
                        "from_request"
                    ]
                },
                "url_param_name": {
                    "type": "string",
                    "maxLength": 64
                },
                "webhook_signature_header": {
                    "type": "string",
                    "maxLength": 128
                },
                "webhook_signature_prefix": {
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "internal_web_adapter_in_http.DryRunRequest": {
            "type": "object",
            "required": [
                "node",
                "request"
            ],
            "properties": {
                "node": {
                    "$ref": "#/definitions/internal_web_adapter_in_http.CreateNodeRequest"
                },
                "request": {
                    "$ref": "#/definitions/internal_web_adapter_in_http.DryRunSubrequest"
                },
                "use_mock": {
                    "type": "boolean"
                }
            }
        },
        "internal_web_adapter_in_http.DryRunSubrequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "method": {
                    "type": "string",
                    "enum": [
                        "GET",
                        "POST",
                        "PUT",
                        "DELETE",
                        "PATCH"
                    ]
                },
                "query": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "internal_web_adapter_in_http.NodeResponse": {
            "type": "object",
            "properties": {
                "auth_credentials_set": {
                    "type": "boolean"
                },
                "auth_dynamic_field": {
                    "type": "string"
                },
                "auth_dynamic_source": {
                    "type": "string"
                },
                "auth_dynamic_strip_prefix": {
                    "type": "string"
                },
                "auth_type": {
                    "type": "string"
                },
                "clickhouse_retention_days": {
                    "type": "integer"
                },
                "clickhouse_table": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "forward_headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "incoming_auth_credentials_set": {
                    "type": "boolean"
                },
                "incoming_auth_type": {
                    "type": "string"
                },
                "log_headers": {
                    "type": "boolean"
                },
                "log_request_body": {
                    "type": "boolean"
                },
                "log_response_body": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "retry_backoff_ms": {
                    "type": "integer"
                },
                "retry_count": {
                    "type": "integer"
                },
                "root_method": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "target_url": {
                    "type": "string"
                },
                "team_id": {
                    "type": "string"
                },
                "timeout_ms": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url_allowed_hosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url_mode": {
                    "type": "string"
                },
                "url_param_name": {
                    "type": "string"
                },
                "webhook_signature_header": {
                    "type": "string"
                },
                "webhook_signature_prefix": {
                    "type": "string"
                }
            }
        },
        "internal_web_adapter_in_http.ReplayRequest": {
            "type": "object",
            "required": [
                "node_id"
            ],
            "properties": {
                "body_override": {
                    "type": "string"
                },
                "custom_auth": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "sync_override": {
                    "type": "boolean"
                },
                "use_node_auth": {
                    "type": "boolean"
                }
            }
        },
        "internal_web_adapter_in_http.UpdateNodeRequest": {
            "type": "object",
            "required": [
                "path",
                "root_method"
            ],
            "properties": {
                "auth_credentials": {
                    "type": "string",
                    "maxLength": 1024
                },
                "auth_dynamic_field": {
                    "type": "string",
                    "maxLength": 64
                },
                "auth_dynamic_source": {
                    "type": "string",
                    "enum": [
                        "query",
                        "header",
                        "body"
                    ]
                },
                "auth_dynamic_strip_prefix": {
                    "type": "string",
                    "maxLength": 64
                },
                "auth_type": {
                    "type": "string",
                    "enum": [
                        "none",
                        "basic",
                        "token",
                        "token_from_request",
                        "basic_from_request"
                    ]
                },
                "clickhouse_retention_days": {
                    "type": "integer",
                    "maximum": 3650,
                    "minimum": 0
                },
                "clickhouse_table": {
                    "type": "string",
                    "maxLength": 129
                },
                "forward_headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "incoming_auth_credentials": {
                    "type": "string",
                    "maxLength": 1024
                },
                "incoming_auth_type": {
                    "type": "string",
                    "enum": [
                        "none",
                        "basic",
                        "token",
                        "webhook_signature"
                    ]
                },
                "log_headers": {
                    "type": "boolean"
                },
                "log_request_body": {
                    "type": "boolean"
                },
                "log_response_body": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string",
                    "maxLength": 255
                },
                "retry_backoff_ms": {
                    "type": "integer"
                },
                "retry_count": {
                    "type": "integer"
                },
                "root_method": {
                    "type": "string",
                    "enum": [
                        "request",
                        "requestAsync"
                    ]
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "enabled",
                        "disabled",
                        "paused"
                    ]
                },
                "target_url": {
                    "type": "string",
                    "maxLength": 2048
                },
                "timeout_ms": {
                    "type": "integer"
                },
                "url_allowed_hosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url_mode": {
                    "type": "string",
                    "enum": [
                        "static",
                        "from_request"
                    ]
                },
                "url_param_name": {
                    "type": "string",
                    "maxLength": 64
                },
                "webhook_signature_header": {
                    "type": "string",
                    "maxLength": 128
                },
                "webhook_signature_prefix": {
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "internal_web_adapter_in_http.changePasswordRequest": {
            "type": "object",
            "required": [
                "new_password"
            ],
            "properties": {
                "must_change_password": {
                    "type": "boolean"
                },
                "new_password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8
                }
            }
        },
        "internal_web_adapter_in_http.createTokenRequest": {
            "type": "object",
            "required": [
                "name",
                "scopes"
            ],
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "scopes": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_web_adapter_in_http.createUserRequest": {
            "type": "object",
            "required": [
                "login",
                "role"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "lang": {
                    "type": "string",
                    "enum": [
                        "en",
                        "ru"
                    ]
                },
                "login": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "must_change_password": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "viewer"
                    ]
                }
            }
        },
        "internal_web_adapter_in_http.loginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                }
            }
        },
        "internal_web_adapter_in_http.updateUserRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "lang": {
                    "type": "string",
                    "enum": [
                        "en",
                        "ru"
                    ]
                },
                "must_change_password": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "viewer"
                    ]
                }
            }
        },
        "internal_web_adapter_in_http.userResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lang": {
                    "type": "string"
                },
                "last_login_at": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "must_change_password": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                },
                "team_id": {
                    "type": "string"
                }
            }
        },
        "nexus_internal_domain.AppSettings": {
            "type": "object",
            "properties": {
                "clickhouse": {
                    "$ref": "#/definitions/nexus_internal_domain.ClickHouseSettings"
                },
                "sentry": {
                    "$ref": "#/definitions/nexus_internal_domain.SentrySettings"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "description": "user_id, кто последним обновил",
                    "type": "string"
                }
            }
        },
        "nexus_internal_domain.ClickHouseSettings": {
            "type": "object",
            "properties": {
                "batch_size": {
                    "type": "integer"
                },
                "buffer_max_size": {
                    "type": "integer"
                },
                "database": {
                    "type": "string"
                },
                "flush_interval_sec": {
                    "type": "integer"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                },
                "workers": {
                    "type": "integer"
                }
            }
        },
        "nexus_internal_domain.SentrySettings": {
            "type": "object",
            "properties": {
                "attach_stacktrace": {
                    "type": "boolean"
                },
                "dsn": {
                    "type": "string"
                },
                "enable_tracing": {
                    "type": "boolean"
                },
                "environment": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "traces_sample_rate": {
                    "type": "number"
                },
                "use": {
                    "type": "boolean"
                }
            }
        },
        "nexus_internal_web_usecase.DryRunReport": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nexus_internal_web_usecase.DryRunStep"
                    }
                }
            }
        },
        "nexus_internal_web_usecase.DryRunStep": {
            "type": "object",
            "properties": {
                "detail": {},
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "ok | failed | skipped",
                    "type": "string"
                }
            }
        },
        "nexus_internal_web_usecase.ReplayResult": {
            "type": "object",
            "properties": {
                "body_preview": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "new_log_id": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "nexus_internal_web_usecase.TestResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "latency_ms": {
                    "type": "integer"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiTokenAuth": {
            "description": "\"Bearer db_\u003c32-байт-base64\u003e\". См. §7.14.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "CookieAuth": {
            "type": "apiKey",
            "name": "nexus_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Nexus Web API",
	Description:      "Admin REST API шины данных (§7 ТЗ). Сессии в Redis +\nAPI-токены (Bearer db_*). SPA по embed.FS отдаётся\nфолбэком на index.html для всех путей не из /api/.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
