// Package web Code generated by swaggo/swag. DO NOT EDIT
package web

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "При успехе ставит HttpOnly cookie databus_session (§7.1 ТЗ).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Логин по логину/паролю.",
                "parameters": [
                    {
                        "description": "credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "invalid credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "user inactive",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/logs/{id}/replay": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Берёт оригинал из ClickHouse-лога, применяет переопределения, отправляет через Receiver.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Повторно отправить запрос через шину (§7.4.1).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "log id (UUID v4)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "опции",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.ReplayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bus_internal_web_usecase.ReplayResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "node disabled",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "429": {
                        "description": "rate limit exceeded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/nodes": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Список узлов команды.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "поиск по path или target_url",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "request | requestAsync",
                        "name": "root_method",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "лимит, max 500",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Только admin. §3.3 ТЗ, лимиты в §3.3.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Создать узел.",
                "parameters": [
                    {
                        "description": "node config",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.CreateNodeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.NodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "path already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/nodes/dry-run": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Прогоняет synthetic-запрос через pipeline шины и возвращает пошаговый отчёт.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Dry-run: проверить конфиг узла без сохранения (§7.5.1).",
                "parameters": [
                    {
                        "description": "node + sub-request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.DryRunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bus_internal_web_usecase.DryRunReport"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/nodes/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Один узел по id.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_web_adapter_in_http.NodeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/nodes/{id}/logs": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    },
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Snapshot логов узла из ClickHouse.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "cursor по date_request (UnixMilli)",
                        "name": "since_ms",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "1..500, default 100",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/nodes/{id}/logs/stream": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Доступно только UI-сессиям (API-токены отклоняются — §7.14). Каждое новое событие приходит как SSE event \"log\".",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "SSE live-tail логов узла (§7.4).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "event-stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bus_internal_web_usecase.DryRunReport": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bus_internal_web_usecase.DryRunStep"
                    }
                }
            }
        },
        "bus_internal_web_usecase.DryRunStep": {
            "type": "object",
            "properties": {
                "detail": {},
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "ok | failed | skipped",
                    "type": "string"
                }
            }
        },
        "bus_internal_web_usecase.ReplayResult": {
            "type": "object",
            "properties": {
                "body_preview": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "new_log_id": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        },
        "internal_web_adapter_in_http.CreateNodeRequest": {
            "type": "object",
            "required": [
                "path",
                "root_method"
            ],
            "properties": {
                "auth_credentials": {
                    "type": "string",
                    "maxLength": 1024
                },
                "auth_dynamic_field": {
                    "type": "string",
                    "maxLength": 64
                },
                "auth_dynamic_source": {
                    "type": "string",
                    "enum": [
                        "query",
                        "header",
                        "body"
                    ]
                },
                "auth_dynamic_strip_prefix": {
                    "type": "string",
                    "maxLength": 64
                },
                "auth_type": {
                    "type": "string",
                    "enum": [
                        "none",
                        "basic",
                        "token",
                        "token_from_request",
                        "basic_from_request"
                    ]
                },
                "clickhouse_retention_days": {
                    "type": "integer",
                    "maximum": 3650,
                    "minimum": 0
                },
                "clickhouse_table": {
                    "type": "string",
                    "maxLength": 129
                },
                "forward_headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "incoming_auth_credentials": {
                    "type": "string",
                    "maxLength": 1024
                },
                "incoming_auth_type": {
                    "type": "string",
                    "enum": [
                        "none",
                        "basic",
                        "token"
                    ]
                },
                "log_headers": {
                    "type": "boolean"
                },
                "log_request_body": {
                    "type": "boolean"
                },
                "log_response_body": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string",
                    "maxLength": 255
                },
                "retry_backoff_ms": {
                    "type": "integer"
                },
                "retry_count": {
                    "type": "integer"
                },
                "root_method": {
                    "type": "string",
                    "enum": [
                        "request",
                        "requestAsync"
                    ]
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "enabled",
                        "disabled",
                        "paused"
                    ]
                },
                "target_url": {
                    "type": "string",
                    "maxLength": 2048
                },
                "timeout_ms": {
                    "type": "integer"
                },
                "url_allowed_hosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url_mode": {
                    "type": "string",
                    "enum": [
                        "static",
                        "from_request"
                    ]
                },
                "url_param_name": {
                    "type": "string",
                    "maxLength": 64
                }
            }
        },
        "internal_web_adapter_in_http.DryRunRequest": {
            "type": "object",
            "required": [
                "node",
                "request"
            ],
            "properties": {
                "node": {
                    "$ref": "#/definitions/internal_web_adapter_in_http.CreateNodeRequest"
                },
                "request": {
                    "$ref": "#/definitions/internal_web_adapter_in_http.DryRunSubrequest"
                },
                "use_mock": {
                    "type": "boolean"
                }
            }
        },
        "internal_web_adapter_in_http.DryRunSubrequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "method": {
                    "type": "string",
                    "enum": [
                        "GET",
                        "POST",
                        "PUT",
                        "DELETE",
                        "PATCH"
                    ]
                },
                "query": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "internal_web_adapter_in_http.NodeResponse": {
            "type": "object",
            "properties": {
                "auth_credentials_set": {
                    "type": "boolean"
                },
                "auth_dynamic_field": {
                    "type": "string"
                },
                "auth_dynamic_source": {
                    "type": "string"
                },
                "auth_dynamic_strip_prefix": {
                    "type": "string"
                },
                "auth_type": {
                    "type": "string"
                },
                "clickhouse_retention_days": {
                    "type": "integer"
                },
                "clickhouse_table": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "forward_headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "incoming_auth_credentials_set": {
                    "type": "boolean"
                },
                "incoming_auth_type": {
                    "type": "string"
                },
                "log_headers": {
                    "type": "boolean"
                },
                "log_request_body": {
                    "type": "boolean"
                },
                "log_response_body": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "retry_backoff_ms": {
                    "type": "integer"
                },
                "retry_count": {
                    "type": "integer"
                },
                "root_method": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "target_url": {
                    "type": "string"
                },
                "team_id": {
                    "type": "string"
                },
                "timeout_ms": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url_allowed_hosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url_mode": {
                    "type": "string"
                },
                "url_param_name": {
                    "type": "string"
                }
            }
        },
        "internal_web_adapter_in_http.ReplayRequest": {
            "type": "object",
            "required": [
                "node_id"
            ],
            "properties": {
                "body_override": {
                    "type": "string"
                },
                "custom_auth": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "sync_override": {
                    "type": "boolean"
                },
                "use_node_auth": {
                    "type": "boolean"
                }
            }
        },
        "internal_web_adapter_in_http.loginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiTokenAuth": {
            "description": "\"Bearer db_\u003c32-байт-base64\u003e\". См. §7.14.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "CookieAuth": {
            "type": "apiKey",
            "name": "databus_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "DataBus Web API",
	Description:      "Admin REST API шины данных (§7 ТЗ). Сессии в Redis +\nAPI-токены (Bearer db_*). SPA по embed.FS отдаётся\nфолбэком на index.html для всех путей не из /api/.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
